# Generated by Django 4.2.6 on 2023-10-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items_count',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
